-- Seed: matrice_status activity catalog (extracted from Matrice Status sheet)
-- project_type values: CEF | CEF cu BESS | BESS in CEF existent | BESS Stand-alone
insert into activities (phase_no, phase_name, name, sort_order, is_section_header, applies_to) values
  (1, 'Racordare (ATR)', 'Aviz Tehnic de Racordare - ATR', 1, false, null),
  (1, 'Racordare (ATR)', 'Studiu de Soluție', 2, false, null),
  (1, 'Racordare (ATR)', 'Proiect + Planșe', 3, false, null),
  (1, 'Racordare (ATR)', 'Contract de Racordare', 4, false, null),
  (2, 'Proiect Tehnic', 'Proiect Tehnic', 5, false, null),
  (2, 'Proiect Tehnic', 'Avizare PT', 6, false, null),
  (3, 'Proiect de Racordare', 'Proiect de Racordare', 7, false, null),
  (3, 'Proiect de Racordare', 'Avizare Racord', 8, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Certificatul de Urbanism', 9, false, null),
  (4, 'Certificat de Urbanism & Avize', 'D.T.A.C', 10, false, null),
  (4, 'Certificat de Urbanism & Avize', 'D.T.O.E', 11, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Aviz MEDIU', 12, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Aviz alimentare energie electrică – Electrica', 13, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Avize amplasament operatori rețele (DEER)', 14, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Aviz Tehnic Racordare DEER', 15, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Acord autentificat proprietari', 16, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Scoatere circuit Agricol – OCPI', 17, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Ministerul Agriculturii', 18, false, null),
  (4, 'Certificat de Urbanism & Avize', 'OSPA', 19, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Aviz Transgaz', 20, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Aviz Sănătatea Populației', 21, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Aviz Romgaz', 22, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Avizul Statului Major General', 23, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Plan Situație Vizat OCPI', 24, false, null),
  (4, 'Certificat de Urbanism & Avize', 'HCL Primărie', 25, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Studiu Geotehnic', 26, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Verificator de Proiecte', 27, false, null),
  (5, 'Depunere Documentație AC', 'Depunere Documentație Obținere AC', 28, false, null),
  (6, 'Autorizație de Construcție', 'Autorizație de Construcție - AC', 29, false, null),
  (7, 'Anunțare Începere Lucrări', 'Anunțare Instituții Începere Lucrări (Primărie + ISCE)', 30, false, null),
  (8, 'Oferte și Comandă Materiale', 'Oferte și Comandă Materiale', 31, true, null),
  (8, 'Oferte și Comandă Materiale', 'BESS', 32, false, array['CEF cu BESS','BESS in CEF existent','BESS Stand-alone']::project_type[]),
  (8, 'Oferte și Comandă Materiale', 'Inverter', 33, false, null),
  (8, 'Oferte și Comandă Materiale', 'HyManager', 34, false, null),
  (8, 'Oferte și Comandă Materiale', 'Panouri Fotovoltaice', 35, false, null),
  (8, 'Oferte și Comandă Materiale', 'Structură Panda/Neo', 36, false, null),
  (8, 'Oferte și Comandă Materiale', 'Transformator', 37, false, null),
  (8, 'Oferte și Comandă Materiale', 'Cablu AC', 38, false, null),
  (8, 'Oferte și Comandă Materiale', 'Cablu DC', 39, false, null),
  (8, 'Oferte și Comandă Materiale', 'Cablu Comunicație', 40, false, null),
  (8, 'Oferte și Comandă Materiale', 'Cutii Colectoare AC', 41, false, null),
  (8, 'Oferte și Comandă Materiale', 'Paratrăsnet', 42, false, null),
  (8, 'Oferte și Comandă Materiale', 'Materiale Consumabile', 43, false, null),
  (8, 'Oferte și Comandă Materiale', 'Materiale RACORDARE', 44, false, null),
  (9, 'Execuție', 'EXECUȚIE', 45, true, null),
  (9, 'Execuție', 'Structură', 46, false, null),
  (9, 'Execuție', 'Împrejmuire – Stâlpuri', 47, false, null),
  (9, 'Execuție', 'Împrejmuire – Panou Bordurat', 48, false, null),
  (9, 'Execuție', 'Batere Stâlpi', 49, false, null),
  (9, 'Execuție', 'Montaj Grinzi Longitudinale', 50, false, null),
  (9, 'Execuție', 'Montaj Grinzi Verticale', 51, false, null),
  (9, 'Execuție', 'Montaj Panouri', 52, false, null),
  (9, 'Execuție', 'Montaj Panouri Fotovoltaice', 53, false, null),
  (9, 'Execuție', 'Montaj Jgheab Metalic / Trasee Cabluri Solare', 54, false, null),
  (9, 'Execuție', 'Realizare Cablaj Stringuri', 55, false, null),
  (9, 'Execuție', 'Cablaj AC + Împământare', 56, false, null),
  (9, 'Execuție', 'Săpături Trasee Cabluri AC', 57, false, null),
  (9, 'Execuție', 'Săpături Trasee Iluminat + Camere Supraveghere', 58, false, null),
  (9, 'Execuție', 'Realizare Împământare (Țăruși + Platbandă)', 59, false, null),
  (9, 'Execuție', 'Pozare Cabluri AC (Forță + Iluminat + Camere)', 60, false, null),
  (9, 'Execuție', 'Fundații + Plantare Stâlpi Iluminat', 61, false, null),
  (9, 'Execuție', 'Montaj Piese Separație + Trasee Împământare + Paratrăsnet', 62, false, null),
  (9, 'Execuție', 'Invertoare + Tablouri', 63, false, null),
  (9, 'Execuție', 'Montaj Invertoare + Tablouri Colectoare AC (TEC)', 64, false, null),
  (9, 'Execuție', 'Realizare Conexiuni Invertoare + TEC', 65, false, null),
  (9, 'Execuție', 'Realizare Conexiuni AC Invertoare', 66, false, null),
  (9, 'Execuție', 'Realizare Conexiuni Tablouri Electrice AC', 67, false, null),
  (9, 'Execuție', 'Realizare Conexiuni TDRI / PTAB', 68, false, null),
  (9, 'Execuție', 'Post Transformare', 69, false, null),
  (9, 'Execuție', 'Fundație Posturi Trafo', 70, false, null),
  (9, 'Execuție', 'Amplasare Posturi Trafo + Macara', 71, false, null),
  (9, 'Execuție', 'Amplasare Transformatoare + Macara', 72, false, null),
  (9, 'Execuție', 'Cablare Posturi Trafo', 73, false, null),
  (9, 'Execuție', 'Verificări Înaintea Recepției', 74, false, null),
  (10, 'Montaj BESS', 'Montaj BESS', 75, true, array['CEF cu BESS','BESS in CEF existent','BESS Stand-alone']::project_type[]),
  (10, 'Montaj BESS', 'Împrejmuire', 76, false, array['CEF cu BESS','BESS in CEF existent','BESS Stand-alone']::project_type[]),
  (10, 'Montaj BESS', 'Iluminat', 77, false, array['CEF cu BESS','BESS in CEF existent','BESS Stand-alone']::project_type[]),
  (10, 'Montaj BESS', 'Sistem de camere', 78, false, array['CEF cu BESS','BESS in CEF existent','BESS Stand-alone']::project_type[]),
  (10, 'Montaj BESS', 'Fundație', 79, false, array['CEF cu BESS','BESS in CEF existent','BESS Stand-alone']::project_type[]),
  (10, 'Montaj BESS', 'Închiriere macara', 80, false, array['CEF cu BESS','BESS in CEF existent','BESS Stand-alone']::project_type[]),
  (10, 'Montaj BESS', 'Cablare', 81, false, array['CEF cu BESS','BESS in CEF existent','BESS Stand-alone']::project_type[]),
  (10, 'Montaj BESS', 'Racord', 82, false, array['CEF cu BESS','BESS in CEF existent','BESS Stand-alone']::project_type[]),
  (11, 'Documentare & Recepție', 'Documentare & Recepție', 83, true, null),
  (11, 'Documentare & Recepție', 'Autorizația de Înființare ANRE (AI)', 84, false, null),
  (11, 'Documentare & Recepție', 'PRE (POD + Contract Furnizare + AI)', 85, false, null),
  (11, 'Documentare & Recepție', 'Recepție Electrica', 86, false, null),
  (11, 'Documentare & Recepție', 'Convenție Exploatare Contor', 87, false, null),
  (11, 'Documentare & Recepție', 'Contract Furnizare Energie POD', 88, false, null),
  (11, 'Documentare & Recepție', 'POD + Contor', 89, false, null),
  (11, 'Documentare & Recepție', 'Cartea Construcțiilor', 90, false, null),
  (12, 'Predare-Primire', 'PREDARE-PRIMIRE', 91, true, null),
  (12, 'Predare-Primire', 'Anunțare Terminare Lucrări (Primărie + ISCE)', 92, false, null),
  (12, 'Predare-Primire', 'PIF + Legare la Rețea', 93, false, null),
  (12, 'Predare-Primire', 'Recepție Contabilitate', 94, false, null),
  (12, 'Predare-Primire', 'Analiză Calitativă', 95, false, null),
  (12, 'Predare-Primire', 'Autorizația de Mediu', 96, false, null),
  (12, 'Predare-Primire', 'NPT', 97, false, null),
  (12, 'Predare-Primire', 'Certificat de Racordare', 98, false, null),
  (12, 'Predare-Primire', 'Licență ANRE', 99, false, null),
  (12, 'Predare-Primire', 'Vânzare Energie', 100, false, null);