-- Seed: matrice_status activity catalog (extracted from Matrice Status sheet)
-- project_type values: CEF | CEF+BESS | BESS | BESS_CEF | EMS | SCADA
insert into activities (phase_no, phase_name, name, sort_order, is_section_header, applies_to) values
  (1, 'Racordare (ATR)', 'Aviz Tehnic de Racordare - ATR', 1, false, null),
  (1, 'Racordare (ATR)', 'Studiu de Soluție', 2, false, null),
  (1, 'Racordare (ATR)', 'Contract de Racordare', 4, false, null),
  (2, 'Proiect Tehnic', 'Proiect Tehnic', 5, false, null),
  (2, 'Proiect Tehnic', 'Avizare PT', 6, false, null),
  (3, 'Proiect de Racordare', 'Proiect de Racordare', 7, false, null),
  (3, 'Proiect de Racordare', 'Avizare Racord', 8, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Certificatul de Urbanism', 9, false, null),
  (4, 'Certificat de Urbanism & Avize', 'D.T.A.C', 10, false, null),
  (4, 'Certificat de Urbanism & Avize', 'D.T.O.E', 11, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Aviz MEDIU', 12, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Aviz alimentare energie electrică – Electrica', 13, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Aviz Tehnic Racordare DEER', 15, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Acord autentificat proprietari', 16, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Scoatere circuit Agricol – OCPI', 17, false, null),
  (4, 'Certificat de Urbanism & Avize', 'OSPA', 19, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Aviz Transgaz', 20, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Aviz Sănătatea Populației', 21, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Aviz Romgaz', 22, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Avizul Statului Major General', 23, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Plan Situație Vizat OCPI', 24, false, null),
  (4, 'Certificat de Urbanism & Avize', 'HCL Primărie', 25, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Studiu Geotehnic', 26, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Verificator de Proiecte', 27, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Acord acces DEER', 28, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Aviz salubritate', 29, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Aviz canalizare', 30, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Localizare certă/incertă', 31, false, null),
  (4, 'Certificat de Urbanism & Avize', 'Dovadă OAR', 32, false, null),
  (5, 'Depunere Documentație AC', 'Depunere Documentație Obținere AC', 33, false, null),
  (6, 'Autorizație de Construcție', 'Autorizație de Construcție - AC', 34, false, null),
  (7, 'Anunțare Începere Lucrări', 'Anunțare Instituții Începere Lucrări (Primărie + ISCE)', 35, false, null),
  (8, 'Oferte și Comandă Materiale', 'Oferte și Comandă Materiale', 36, true, null),
  (8, 'Oferte și Comandă Materiale', 'BESS', 37, false, array['CEF+BESS','BESS','BESS_CEF']::project_type[]),
  (8, 'Oferte și Comandă Materiale', 'Inverter', 38, false, null),
  (8, 'Oferte și Comandă Materiale', 'Panouri Fotovoltaice', 39, false, null),
  (8, 'Oferte și Comandă Materiale', 'Structură', 40, false, null),
  (8, 'Oferte și Comandă Materiale', 'Transformator', 41, false, null),
  (8, 'Oferte și Comandă Materiale', 'Cablu AC', 42, false, null),
  (8, 'Oferte și Comandă Materiale', 'Cablu DC', 43, false, null),
  (8, 'Oferte și Comandă Materiale', 'Cablu Comunicație', 44, false, null),
  (8, 'Oferte și Comandă Materiale', 'Cutii Colectoare AC', 45, false, null),
  (8, 'Oferte și Comandă Materiale', 'Paratrăsnet', 46, false, null),
  (8, 'Oferte și Comandă Materiale', 'Materiale Consumabile', 47, false, null),
  (8, 'Oferte și Comandă Materiale', 'Materiale RACORDARE', 48, false, null),
  (9, 'Execuție', 'EXECUȚIE', 49, true, null),
  (9, 'Execuție', 'Structură', 50, false, null),
  (9, 'Execuție', 'Împrejmuire – Stâlpuri', 51, false, null),
  (9, 'Execuție', 'Împrejmuire – Panou Bordurat', 52, false, null),
  (9, 'Execuție', 'Batere Stâlpi', 53, false, null),
  (9, 'Execuție', 'Montaj Grinzi Longitudinale', 54, false, null),
  (9, 'Execuție', 'Montaj Grinzi Verticale', 55, false, null),
  (9, 'Execuție', 'Montaj Panouri', 56, false, null),
  (9, 'Execuție', 'Montaj Panouri Fotovoltaice', 57, false, null),
  (9, 'Execuție', 'Montaj Jgheab Metalic / Trasee Cabluri Solare', 58, false, null),
  (9, 'Execuție', 'Realizare Cablaj Stringuri', 59, false, null),
  (9, 'Execuție', 'Cablaj AC + Împământare', 60, false, null),
  (9, 'Execuție', 'Săpături Trasee Cabluri AC', 61, false, null),
  (9, 'Execuție', 'Săpături Trasee Iluminat + Camere Supraveghere', 62, false, null),
  (9, 'Execuție', 'Realizare Împământare (Țăruși + Platbandă)', 63, false, null),
  (9, 'Execuție', 'Pozare Cabluri AC (Forță + Iluminat + Camere)', 64, false, null),
  (9, 'Execuție', 'Fundații + Plantare Stâlpi Iluminat', 65, false, null),
  (9, 'Execuție', 'Montaj Piese Separație + Trasee Împământare + Paratrăsnet', 66, false, null),
  (9, 'Execuție', 'Invertoare + Tablouri', 67, false, null),
  (9, 'Execuție', 'Montaj Invertoare + Tablouri Colectoare AC (TEC)', 68, false, null),
  (9, 'Execuție', 'Realizare Conexiuni Invertoare + TEC', 69, false, null),
  (9, 'Execuție', 'Realizare Conexiuni AC Invertoare', 70, false, null),
  (9, 'Execuție', 'Realizare Conexiuni Tablouri Electrice AC', 71, false, null),
  (9, 'Execuție', 'Realizare Conexiuni TDRI / PTAB', 72, false, null),
  (9, 'Execuție', 'Post Transformare', 73, false, null),
  (9, 'Execuție', 'Fundație Posturi Trafo', 74, false, null),
  (9, 'Execuție', 'Amplasare Posturi Trafo + Macara', 75, false, null),
  (9, 'Execuție', 'Amplasare Transformatoare + Macara', 76, false, null),
  (9, 'Execuție', 'Cablare Posturi Trafo', 77, false, null),
  (9, 'Execuție', 'Verificări Înaintea Recepției', 78, false, null),
  (10, 'Montaj BESS', 'Montaj BESS', 79, true, array['CEF+BESS','BESS','BESS_CEF']::project_type[]),
  (10, 'Montaj BESS', 'Împrejmuire', 80, false, array['CEF+BESS','BESS','BESS_CEF']::project_type[]),
  (10, 'Montaj BESS', 'Iluminat', 81, false, array['CEF+BESS','BESS','BESS_CEF']::project_type[]),
  (10, 'Montaj BESS', 'Sistem de camere', 82, false, array['CEF+BESS','BESS','BESS_CEF']::project_type[]),
  (10, 'Montaj BESS', 'Fundație', 83, false, array['CEF+BESS','BESS','BESS_CEF']::project_type[]),
  (10, 'Montaj BESS', 'Închiriere macara', 84, false, array['CEF+BESS','BESS','BESS_CEF']::project_type[]),
  (10, 'Montaj BESS', 'Cablare', 85, false, array['CEF+BESS','BESS','BESS_CEF']::project_type[]),
  (10, 'Montaj BESS', 'Racord', 86, false, array['CEF+BESS','BESS','BESS_CEF']::project_type[]),
  (11, 'Documentare & Recepție', 'Documentare & Recepție', 87, true, null),
  (11, 'Documentare & Recepție', 'Cartea Construcțiilor', 88, false, null),
  (11, 'Documentare & Recepție', 'Recepție Electrica', 89, false, null),
  (11, 'Documentare & Recepție', 'Convenție Exploatare Contor', 90, false, null),
  (11, 'Documentare & Recepție', 'Contract Furnizare Energie POD', 91, false, null),
  (11, 'Documentare & Recepție', 'POD + Contor', 92, false, null),
  (11, 'Documentare & Recepție', 'PRE (POD + Contract Furnizare + AI)', 93, false, null),
  (11, 'Documentare & Recepție', 'Autorizația de Înființare ANRE (AI)', 94, false, null),
  (12, 'Predare-Primire', 'PREDARE-PRIMIRE', 95, true, null),
  (12, 'Predare-Primire', 'Anunțare Terminare Lucrări (Primărie + ISCE)', 96, false, null),
  (12, 'Predare-Primire', 'PIF + Legare la Rețea', 97, false, null),
  (12, 'Predare-Primire', 'Recepție Contabilitate', 98, false, null),
  (12, 'Predare-Primire', 'Analiză Calitativă', 99, false, null),
  (12, 'Predare-Primire', 'Autorizația de Mediu', 100, false, null),
  (12, 'Predare-Primire', 'NPT', 101, false, null),
  (12, 'Predare-Primire', 'Certificat de Racordare', 102, false, null),
  (12, 'Predare-Primire', 'Licență ANRE', 103, false, null),
  (12, 'Predare-Primire', 'Vânzare Energie', 104, false, null);