-- Build the entire Matrice catalog from scratch to match the
-- "Matrice Status si Documente" PDF exactly, using the PDF's own 1-10
-- top-level phase numbering and item order verbatim. Both
-- matrice_phases and activities were emptied (confirmed intentional)
-- before this migration, so every id is freshly generated — no
-- relocation/rename/id-preservation logic is needed.
--
-- Generated by scripts/_gen_matrice_fresh_build.mjs — every sort_order
-- below is a simple 1-based counter computed by the generator, never
-- hand-typed, so duplicate/colliding positions are structurally
-- impossible.

insert into public.matrice_phases (name, sort_order, service_type, gantt_phase_key) values
  ('Certificatul de Urbanism - CU', 1, 'proiectare', 'planning'),
  ('Aviz Tehnic de racordare -ATR', 2, 'proiectare', 'planning'),
  ('Autorizație de construcție', 3, 'proiectare', 'planning'),
  ('Proiect de executie construire', 4, 'proiectare', 'planning'),
  ('Proiect Racord 20 kV', 5, 'proiectare', 'planning'),
  ('Proiect Utilizare 0.4/0.8kV', 6, 'proiectare', 'planning'),
  ('Proiect de ALO', 7, 'proiectare', 'planning'),
  ('Oferte și comanda materiale', 8, 'executie', 'execution'),
  ('Executie', 9, 'executie', 'execution'),
  ('BESS', 10, 'executie', 'execution'),
  ('RECEPTIE SI AUTORIZARE', 11, 'executie', 'autorizare');

-- Activities, one insert block per phase (phase_id resolved by name).
-- Phase: Certificatul de Urbanism - CU
insert into public.activities (phase_id, name, sort_order, is_section_header, applies_to, is_aviz, expires_required)
select id, v.name, v.sort_order, v.is_section_header, null, v.is_aviz, v.expires_required
from public.matrice_phases, (values
  ('Aviz MEDIU', 1, false, true, true),
  ('Aviz de amplasament DEER', 2, false, true, true),
  ('Aviz de amplasament Transelectrica', 3, false, true, true),
  ('Aviz Tehnic de Racordare (DEER)', 4, false, true, true),
  ('Scoatere din circuit Agricol', 5, false, false, false),
  ('Studiu pedologic-OSPA', 6, false, false, false),
  ('Aviz ANIF', 7, false, true, true),
  ('Plan de situatie Vizat OCPI', 8, false, false, false),
  ('Aviz Romgaz', 9, false, true, true),
  ('Aviz Transgaz', 10, false, true, true),
  ('Aviz Delgaz', 11, false, true, true),
  ('Aviz CFR', 12, false, true, true),
  ('Aviz Aquaserv', 13, false, true, true),
  ('Aviz ABA', 14, false, true, true),
  ('Aviz Telecomunicatie (DIGI, Orange, Vodafone)', 15, false, true, true),
  ('Aviz CNAIR', 16, false, true, true),
  ('Aviz Directia Tehnica CJ Mures', 17, false, true, true),
  ('Aviz Sanatatea populatiei', 18, false, true, true),
  ('Avizul Statului Major General', 19, false, true, true),
  ('Studio Geotehnic', 20, false, false, false),
  ('Hotare Consiliul Local Primarie', 21, false, false, false),
  ('Acordul autentificat al proprietarilor', 22, false, false, false)
) as v(name, sort_order, is_section_header, is_aviz, expires_required)
where matrice_phases.name = 'Certificatul de Urbanism - CU';

-- Phase: Aviz Tehnic de racordare -ATR
insert into public.activities (phase_id, name, sort_order, is_section_header, applies_to, is_aviz, expires_required)
select id, v.name, v.sort_order, v.is_section_header, null, v.is_aviz, v.expires_required
from public.matrice_phases, (values
  ('Studiu de solutie', 1, false, false, false),
  ('Contract de racordare', 2, false, false, false)
) as v(name, sort_order, is_section_header, is_aviz, expires_required)
where matrice_phases.name = 'Aviz Tehnic de racordare -ATR';

-- Phase: Autorizație de construcție
insert into public.activities (phase_id, name, sort_order, is_section_header, applies_to, is_aviz, expires_required)
select id, v.name, v.sort_order, v.is_section_header, null, v.is_aviz, v.expires_required
from public.matrice_phases, (values
  ('D.T.A.C.', 1, false, false, false),
  ('D.T.O.E', 2, false, false, false),
  ('Deviz general', 3, false, false, true),
  ('Ce specialitati facem * ( AHITECTURA / REZISTENTA ) sau daca are sa puna la dispozitie', 4, false, false, false),
  ('Anunțare Începerea Lucrări (Primărie + ISCE)', 5, false, false, false),
  ('Autorizația de înființare ANRE (AI)', 6, false, false, true)
) as v(name, sort_order, is_section_header, is_aviz, expires_required)
where matrice_phases.name = 'Autorizație de construcție';

-- Phase: Proiect de executie construire
insert into public.activities (phase_id, name, sort_order, is_section_header, applies_to, is_aviz, expires_required)
select id, v.name, v.sort_order, v.is_section_header, null, v.is_aviz, v.expires_required
from public.matrice_phases, (values
  ('Proiect de arhitectura - Faza : P.Th.', 1, false, false, false),
  ('Proiect de structura - Faza : P.Th.', 2, false, false, false),
  ('Proiect de electrice - Faza : P.Th.', 3, false, false, false),
  ('Verificare proiecte cu verificatori atestati in cosntructii', 4, false, false, false)
) as v(name, sort_order, is_section_header, is_aviz, expires_required)
where matrice_phases.name = 'Proiect de executie construire';

-- Phase: Proiect Racord 20 kV
insert into public.activities (phase_id, name, sort_order, is_section_header, applies_to, is_aviz, expires_required)
select id, v.name, v.sort_order, v.is_section_header, null, v.is_aviz, v.expires_required
from public.matrice_phases, (values
  ('Proiect Racord : Faza P.TH - Verificat', 1, false, false, false),
  ('Drept de servitute', 2, false, false, true),
  ('Avizare Proiect Racord', 3, false, false, false)
) as v(name, sort_order, is_section_header, is_aviz, expires_required)
where matrice_phases.name = 'Proiect Racord 20 kV';

-- Phase: Proiect Utilizare 0.4/0.8kV
insert into public.activities (phase_id, name, sort_order, is_section_header, applies_to, is_aviz, expires_required)
select id, v.name, v.sort_order, v.is_section_header, null, v.is_aviz, v.expires_required
from public.matrice_phases, (values
  ('Proiect Utilizare : Faza P.TH - Verificat', 1, false, false, false),
  ('Avizare Proiect Utilizare', 2, false, false, false)
) as v(name, sort_order, is_section_header, is_aviz, expires_required)
where matrice_phases.name = 'Proiect Utilizare 0.4/0.8kV';

-- Phase: Proiect de ALO
insert into public.activities (phase_id, name, sort_order, is_section_header, applies_to, is_aviz, expires_required)
select id, v.name, v.sort_order, v.is_section_header, null, v.is_aviz, v.expires_required
from public.matrice_phases, (values
  ('Proiect Utilizare : Faza P.TH - Verificat', 1, false, false, false),
  ('Avizare Proiect ALO', 2, false, false, false)
) as v(name, sort_order, is_section_header, is_aviz, expires_required)
where matrice_phases.name = 'Proiect de ALO';

-- Phase: Oferte și comanda materiale
insert into public.activities (phase_id, name, sort_order, is_section_header, applies_to, is_aviz, expires_required)
select id, v.name, v.sort_order, v.is_section_header, null, v.is_aviz, v.expires_required
from public.matrice_phases, (values
  ('Oferte și comanda materiale', 1, true, false, false),
  ('BESS', 2, false, false, false),
  ('Inverter', 3, false, false, false),
  ('Panouri fotovoltaice', 4, false, false, false),
  ('Structura', 5, false, false, false),
  ('Transformatoare', 6, false, false, false),
  ('Posturi Trafo', 7, false, false, false),
  ('Cablu AC', 8, false, false, false),
  ('Cablu DC', 9, false, false, false),
  ('Cablu de comunicatie', 10, false, false, false),
  ('Cuti colectoare AC', 11, false, false, false),
  ('Paratraznet', 12, false, false, false),
  ('Materiale consumabile', 13, false, false, false),
  ('Materiale racordare', 14, false, false, false)
) as v(name, sort_order, is_section_header, is_aviz, expires_required)
where matrice_phases.name = 'Oferte și comanda materiale';

-- Phase: Executie
insert into public.activities (phase_id, name, sort_order, is_section_header, applies_to, is_aviz, expires_required)
select id, v.name, v.sort_order, v.is_section_header, null, v.is_aviz, v.expires_required
from public.matrice_phases, (values
  ('Executie', 1, true, false, false),
  ('Plan trasare amplasament', 2, false, false, false),
  ('Pichetare amplasament', 3, false, false, false),
  ('Structură', 4, false, false, false),
  ('Împrejmuire – Stâlpuri', 5, false, false, false),
  ('Împrejmuire – Panou Bordurat', 6, false, false, false),
  ('Batere Stâlpi', 7, false, false, false),
  ('Montaj Grinzi Longitudinale', 8, false, false, false),
  ('Montaj Grinzi Verticale', 9, false, false, false),
  ('Montaj Panouri Fotovoltaice', 10, false, false, false),
  ('Montaj Jgheab Metalic / Trasee Cabluri Solare', 11, false, false, false),
  ('Realizare Cablaj Stringuri', 12, false, false, false),
  ('Cablaj AC + Împământare', 13, false, false, false),
  ('Săpături Trasee Cabluri AC', 14, false, false, false),
  ('Săpături Trasee Iluminat + Camere Supraveghere', 15, false, false, false),
  ('Realizare Împământare (Țăruși + Platbandă)', 16, false, false, false),
  ('Pozare Cabluri AC (Forță + Iluminat + Camere)', 17, false, false, false),
  ('Fundații + Plantare Stâlpi Iluminat', 18, false, false, false),
  ('Montaj Piese Separație + Trasee Împământare + Paratrăsnet', 19, false, false, false),
  ('Invertoare + Tablouri', 20, false, false, false),
  ('Montaj Invertoare + Tablouri Colectoare AC (TEC)', 21, false, false, false),
  ('Realizare Conexiuni Invertoare + TEC', 22, false, false, false),
  ('Realizare Conexiuni AC Invertoare', 23, false, false, false),
  ('Realizare Conexiuni Tablouri Electrice AC', 24, false, false, false),
  ('Realizare Conexiuni TDRI / PTAB', 25, false, false, false),
  ('Post Transformare', 26, false, false, false),
  ('Fundație Posturi Trafo', 27, false, false, false),
  ('Amplasare Posturi Trafo + Macara', 28, false, false, false),
  ('Amplasare Transformatoare + Macara', 29, false, false, false),
  ('Cablare Posturi Trafo', 30, false, false, false),
  ('Verificări Înaintea Recepției', 31, false, false, false)
) as v(name, sort_order, is_section_header, is_aviz, expires_required)
where matrice_phases.name = 'Executie';

-- Phase: BESS
insert into public.activities (phase_id, name, sort_order, is_section_header, applies_to, is_aviz, expires_required)
select id, v.name, v.sort_order, v.is_section_header, array['CEF+BESS','BESS','BESS_CEF']::project_type[], v.is_aviz, v.expires_required
from public.matrice_phases, (values
  ('BESS', 1, true, false, false),
  ('Plan trasare amplasament', 2, false, false, false),
  ('Pichetare amplasament', 3, false, false, false),
  ('Împrejmuire', 4, false, false, false),
  ('Iluminat', 5, false, false, false),
  ('Sistem de camere', 6, false, false, false),
  ('Fundație', 7, false, false, false),
  ('Închiriere macara', 8, false, false, false),
  ('Cablare', 9, false, false, false),
  ('Racord', 10, false, false, false)
) as v(name, sort_order, is_section_header, is_aviz, expires_required)
where matrice_phases.name = 'BESS';

-- Phase: RECEPTIE SI AUTORIZARE
insert into public.activities (phase_id, name, sort_order, is_section_header, applies_to, is_aviz, expires_required)
select id, v.name, v.sort_order, v.is_section_header, null, v.is_aviz, v.expires_required
from public.matrice_phases, (values
  ('RECEPTIE SI AUTORIZARE', 1, true, false, false),
  ('Cartea Constructiilor', 2, false, false, false),
  ('Anuntare terminarea lucrariilor Primaria + ISCE', 3, false, false, false),
  ('Conventie de exploatare', 4, false, false, false),
  ('Receptie DEER', 5, false, false, false),
  ('PIF+legare la rețea', 6, false, false, false),
  ('Aviz Tehnic de Racordare PROBE', 7, false, true, true),
  ('Emitete POD DEER', 8, false, false, false),
  ('Contract furnizare energie pt POD', 9, false, false, false),
  ('Contor DEER', 10, false, false, false),
  ('Recepție Contabilitate', 11, false, false, false),
  ('Anunțare Terminare Lucrări (Primărie + ISCE)', 12, false, false, false),
  ('PRE - este necesar POD+ Ctr furnizare + AI', 13, false, false, false),
  ('Notificare de Punere sub Tensiune -NPT', 14, false, false, false),
  ('Analiza calitativa', 15, false, false, false),
  ('Certificat de racordare', 16, false, false, false),
  ('Autorizatia de Mediu', 17, false, false, false),
  ('Licență ANRE', 18, false, true, true),
  ('Vânzare energie', 19, false, false, false)
) as v(name, sort_order, is_section_header, is_aviz, expires_required)
where matrice_phases.name = 'RECEPTIE SI AUTORIZARE';

select public.recompute_all_project_progress();

-- Fail loudly instead of shipping a silently-broken order.
do $$
declare
  dup record;
  phase_count int;
  activity_count int;
begin
  for dup in
    select phase_id, sort_order, count(*) as n
    from public.activities group by phase_id, sort_order having count(*) > 1
  loop
    raise exception 'duplicate sort_order % in phase % (% rows)', dup.sort_order, dup.phase_id, dup.n;
  end loop;
  for dup in
    select sort_order, count(*) as n
    from public.matrice_phases group by sort_order having count(*) > 1
  loop
    raise exception 'duplicate matrice_phases.sort_order % (% rows)', dup.sort_order, dup.n;
  end loop;
  select count(*) into phase_count from public.matrice_phases;
  select count(*) into activity_count from public.activities;
  if phase_count != 11 then
    raise exception 'expected 11 phases, found %', phase_count;
  end if;
  if activity_count != 115 then
    raise exception 'expected 115 activities, found %', activity_count;
  end if;
end $$;
